# syntax=docker/dockerfile:1.7
# Vast.ai native-container adaptation of MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark.
# No Docker-in-Docker: the MiaAI patches are baked directly into the runtime image.

ARG BASE_IMAGE="ghcr.io/0xsero/deepseek-v4-flash-0731-spark-sparkinfer@sha256:2e077489a83a0360952828051fe7f7a32c1801e5ce8436d85f7267583d614ff4"
FROM ${BASE_IMAGE}

# Pin the exact MiaAI-Lab commit used to construct this adaptation.
# MiaAI-Lab commit: fdcd538fbf95fb15b2d6850db9613d22b2c889b8

# These are the exact bind-mount overrides generated by MiaAI-Lab/start.sh,
# converted into image layers so the container can run directly on Vast.ai.
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/image-patch/coalesce_rank_sliced_exl3.py /opt/recipe/scripts/coalesce_rank_sliced_exl3.py
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/image-patch/sparkinfer/moe/fused_moe/_impl.py /opt/sparkinfer/sparkinfer/moe/fused_moe/_impl.py
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/image-patch/sparkinfer/moe/_shared/kernels/tiny_decode.py /opt/sparkinfer/sparkinfer/moe/_shared/kernels/tiny_decode.py
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/image-patch/entrypoint-toolfix.sh /patch-run-entrypoint.sh
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/image-patch/serve-ds4-flash.sh /opt/vllm/serve-ds4-flash.sh
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/image-patch/vllm/models/deepseek_v4/nvidia/dspark.py /opt/vllm/vllm/models/deepseek_v4/nvidia/dspark.py
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/image-patch/sparkinfer/attention/_shared/mla/prefill.py /opt/sparkinfer/sparkinfer/attention/_shared/mla/prefill.py
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/image-patch/sparkinfer/attention/_shared/mla/prefill_mg.py /opt/sparkinfer/sparkinfer/attention/_shared/mla/prefill_mg.py
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/image-patch/entrypoint-256k.sh /opt/recipe/scripts/entrypoint.sh
ADD https://raw.githubusercontent.com/MiaAI-Lab/DeepSeek-v4-Flash-One-DGX-Spark/fdcd538fbf95fb15b2d6850db9613d22b2c889b8/LICENSE /licenses/MiaAI-Lab-DeepSeek-v4-Flash-One-DGX-Spark.LICENSE

COPY vast-entrypoint.sh /vast-entrypoint.sh

# Remote ADD does not preserve the executable bit reliably. The Mia recipe
# executes serve-ds4-flash.sh directly, so make all shell entrypoints executable.
RUN chmod 0755 \
    /vast-entrypoint.sh \
    /patch-run-entrypoint.sh \
    /opt/recipe/scripts/entrypoint.sh \
    /opt/vllm/serve-ds4-flash.sh

# Defaults mirror MiaAI-Lab/start.sh (ABLATE=0 path).
ENV HF_HOME=/hf-cache \
    PORT=8888 \
    HOST=0.0.0.0 \
    SERVED_MODEL_NAME=deepseek-v4-flash-0731 \
    MODEL_REPO=0xSero/deepseek-v4-flash-0731-spark \
    MODEL_REVISION=22f28d32b9b29b4352eaa380ff8c2c170b2847ab \
    MODEL_SOURCE_DIR=/hf-cache/hub/models--0xSero--deepseek-v4-flash-0731-spark/snapshots/22f28d32b9b29b4352eaa380ff8c2c170b2847ab \
    MODEL_PATH=/models/tp1 \
    SPEC_MODEL_PATH=/models/dspark-draft-k64 \
    MAX_MODEL_LEN=156000 \
    MAX_NUM_SEQS=1 \
    MAX_NUM_BATCHED_TOKENS=8224 \
    VLLM_DSV4_PADDED_NVFP4=0 \
    KV_FP8_ROPE=0 \
    MODE=dspark \
    DSPARK_TOKENS=5 \
    DSPARK_CAPACITY=0 \
    DSPARK_DYNAMIC_DRAFT_DEPTH=0 \
    DSPARK_DYNAMIC_DRAFT_DEPTH_WINDOW=8 \
    DSPARK_DRAFT_EXPERTS=64 \
    DSPARK_STRUCTURED_EXPERTS_PER_CATEGORY=32 \
    VLLM_USE_B12X_WO_PROJECTION=1 \
    GPU_MEMORY_UTILIZATION=0.905 \
    VERIFY_MODEL_CHECKSUMS=1 \
    MAX_CUDAGRAPH_CAPTURE_SIZE=24 \
    CUDAGRAPH_CAPTURE_SIZES=6,12,24 \
    VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0 \
    EXTRA_VLLM_ARGS="--long-prefill-token-threshold 1024" \
    DEFAULT_CHAT_TEMPLATE_KWARGS_THINKING=true \
    DEFAULT_CHAT_TEMPLATE_KWARGS_EFFORT=max \
    KV_OFFLOAD_GB=0 \
    VLLM_USE_SIMPLE_KV_OFFLOAD=0

EXPOSE 8888

# Vast.ai should use the "docker ENTRYPOINT" launch mode for this image.
ENTRYPOINT ["/bin/bash", "/vast-entrypoint.sh"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=20m --retries=3 \
  CMD curl -fsS --max-time 5 http://127.0.0.1:8888/health || exit 1
